### PR TITLE
Multi arch

### PR DESCRIPTION
**Pull request by whatever4711**
Created the goals `all` and `all_push`, which will iterate over the architectures defined in the variable `ARCHITECTURES`. Moreover, I added a `VERSION` to the plugin, which should be fixed for any future Kathara release. It produces the plugin with the name `kathara/katharanp:<arch>-$(VERSION)`.

### CODE REVIEW

**Comment by Skazza94** [comment]
Hi @whatever4711,
thanks for the PR. @lorenzo93 will take care of it since he wrote all the multi-arch stuff.

**Comment by lorenzo93** [comment]
Hi @whatever4711 ,

@Skazza94 did a small mistake and closed the PR.
I'm reopening it :)

**Comment by lorenzo93** [comment]
Hi @whatever4711 ,

I'm sorry for the conflict, but you create the PR on a developing branch that was already merged and we forgot to delete.

I'm perfectly fine with adding all the possible architectures and the relative goals `all` and `all_push`.
On the other hand, I'm not so sure about adding the version to the tag. Doing this, Kathará needs to know which is the latest version each time to install the correct plugin.
Moreover, we never made changes that breaks compatibility so there is no need to use an older version.

We'll think about this in the next days :)

**Comment by Skazza94** [comment]
Hi @whatever4711,
we came to the conclusion that it is better to not include the version number into the plugin tag.
However, your changes for adding all the possible architectures is good. So, if you want, resolve conflicts and then we'll also merge this PR.

Thanks,
Mariano.

**Pull request closed without merging**
